spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project
    username: root
    password: Leavemealone13
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
logging:
  level:
    root: INFO
    com.com.xask: TRACE
  file:
    name: D:/Проект/PROJECT_SECURITY_DB/src/main/java/com/xask/logs/application.log
    path:
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 5
      total-size-cap: 50MB
